apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.fullname" . }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.config.saPassword | quote }}
