apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iowa.fullname" . }}-db-secrets
  labels:
    {{- include "iowa.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.sqlserver.enabled }}
  sqlserver-sa-password: {{ .Values.sqlserver.auth.saPassword | quote }}
  {{- end }}
